---
galaxy_info:
  role_name: linux_netbox
  namespace: a118n
  author: Daniel Allen
  description: Install NetBox
  license: GPL-3.0-only
  min_ansible_version: 2.9
  platforms:
    - name: RHEL
      versions:
        - 8
  galaxy_tags: []
dependencies: []
