---
- name: Install base roles on all Linux servers
  hosts: linux
  become: true
  roles:
    # - role: ../roles/linux_base
    #   vars:
    #     use_proxy: false
    #     use_ssl_certificate: false
    #     join_domain: false

    # - role: ../roles/linux_cockpit
    #   vars:
    #     use_ssl_certificate: false
    #     cockpit_port: 9091

    # - role: ../roles/linux_redis
    #   vars:
    #     redis_version: 6.2.6
    #     redis_port: 6379

    - role: ../roles/linux_postgresql
      vars:
        postgresql_version: 14
