---
- name: Template
  hosts: test
  tasks:
    - name: Print hostname
      ansible.builtin.debug:
        var: ansible_hostname
  roles:
    - role: ../roles/linux_base
      vars:
        use_proxy: false
        use_ssl_certificate: false
        join_domain: false

    - role: ../roles/linux_cockpit
      vars:
        use_ssl_certificate: false
        cockpit_port: 9090
